### ISSUE TITLE
Visual Studio Code Crashing

### ISSUE THREAD

**Issue by jaimik64** [hikarin522/GlassIt-VSC#24]
I've Installed this extension and from now on it keep crashing my visual studio code eachtime. Visual code open only for 1-2 minutes then it crash.
Hopefully, This Get Updated Soon.....

**Comment by whizsid** [comment]
Can you provide below details?

- Operating System and Version
- GlassIt extension version
- VSC version.

**Comment by jaimik64** [comment]
Thank you for your email.
But I've problem with visual studio code it not working properly.
It's not extension problem I just misunderstood.
