### ISSUE TITLE
command 'glassit.increase' not found

### ISSUE THREAD

**Issue by thiensniper** [hikarin522/GlassIt-VSC#3]
Can't increase or decrease the transparency.

**Comment by tariva** [comment]
getting same error with ctrl + calt + z

**Comment by thiensniper** [comment]
@tariva I think this extension hasn't compatible with the new version of visual code that we have yet!

**Comment by zeferinix-mllrdev** [comment]
@thiensniper Same issue. A co-worker of mine have the same latest version as of date and it works fine on his machine. I think this is machine-specific and not compatibility issue with newer versions of visual studio code.

**Comment by thiensniper** [comment]
@zeferinix-mllrdev I try the extension on 2 machine. One is desktop PC, one is on laptop. The desktop PC use Ubuntu 16.04 and the laptop use Windows 10. And both of them can't increase or decrease the transparency.

**Comment by thiensniper** [comment]
@zeferinix-mllrdev  @tariva The issue was resolve automatically when i updated Windows 10 to 1803. I haven't try on ubuntu if it working on yet!

**Comment by AbhimanyuAryan** [comment]
doesn't work in macOS High Sierra either

**Comment by houtaru** [comment]
i'm getting same error!

**Comment by hiteshsahu** [comment]
Same issue on Ubuntu 18 with VS 1.29.1  for GlassIt-VSC v0.1.3

**Comment by hikarin522** [comment]
This extension supports Windows only.
So I fixed it to work only in Windows environment.

v0.1.4

**Comment by felloz** [comment]
I have same issue, using Windows VS Code version 1.45.1

**Comment by cerino-ligutom** [comment]
> I have same issue, using Windows VS Code version 1.45.1

Same VS Code version, it works fine on my machine and still using it (more than 2 years). Win10 Pro 64bit. Maybe you have something else going on? 

I had this issue at my work desktop when the OS was running on Win10 2016 LTSB. Was gone when we moved to Windows pro. There could've been something missing in that OS that this extension requires.

**Comment by TanawatJukmongkol** [comment]
Have same issue in Codium 1.65.2, on ParrotOS. :/

**Comment by Isok-Yashy** [comment]
has the same effect https://marketplace.visualstudio.com/items?itemName=eyhn.vscode-vibrancy

**Comment by Brayden-L** [comment]
Same issue with VSCodium version 1.67.2 built on Gentoo Linux. I will likely manually set a transparency value for VSCodium in my compositor; I suggest people viewing this thread do the same.

**Comment by SW-WANTED** [comment]
command 'glassit.increase' not found

**Comment by v-nhandt21** [comment]
Ctrl + Shift + P

Then open UI Setting, search for Glassit, and set the transparency value

![image](https://user-images.githubusercontent.com/36092323/194465720-f918a011-386f-4d68-80b2-12c5ea1f7e3e.png)

**Comment by boullbane** [comment]
@v-nhandt21 still not work for me
