### ISSUE TITLE
Transparency not going away even after uninstalling extension , deleting the Vscode settings 

### ISSUE THREAD

**Issue by Dipankar-Kumar-Singh** [hikarin522/GlassIt-VSC#31]
Issue Type: Bug

I earlier used an Extension [ GlassIt-VSC ],then uninstalled It,
But its changes were not gone [ transparency was still there ]
I reInstalled it to decrease the transparency as much as possible to make it look like Default VS Code, But Still, some transparency was there,
I Uninstalled VS Code, Deleted ALL its Cached Files, Reinstalled.
Then also that effect was not going away,
I deleted the VS code Settings' JSON File's ALL content.
I thought Finally, I would be able to get rid of it, But It somehow again came back [ Transparency ] 😓

VS Code version: Code 1.61.0 (ee8c7de, 2021-10-07T18:13:09.652Z)
OS version: Windows_NT x64 10.0.22471
Restricted Mode: No

**Comment by everdrone** [comment]
@dipankarcode were you able to solve this problem? I'm having the same issue
