### ISSUE TITLE
[Feature] Wayland / Sway support

### ISSUE THREAD

**Issue by ckcr4lyf** [hikarin522/GlassIt-VSC#43]
I use Sway (Compositor for Wayland) on Arch Linux. Since VS Code runs natively in Wayland, the given linux script using `xprop` etc. doesn't work. 

Would you accept a PR adding support for sway?

**Comment by RannyBergamotte** [comment]
Any possibility of adding support for other WayLand composistors (eg. Kwin, Mutter, any WlRoots based compositors)? I am right now using both Kwin and Hyprland and neither seems to work with GlassIt after enabling the forcesway option.

**Comment by ckcr4lyf** [comment]
> I am right now using both Kwin and Hyprland and neither seems to work with GlassIt after enabling the forcesway option.

@RannyBergamotte you could look into how your compositor supports opacity / transparency and then see if you can make it work, it might be different than how sway does it (e.g. sway has a command for it which can be sent via swaymsg)

**Comment by luxluth** [comment]
> Any possibility of adding support for other WayLand composistors (eg. Kwin, Mutter, any WlRoots based compositors)? I am right now using both Kwin and Hyprland and neither seems to work with GlassIt after enabling the forcesway option.

On hyprland, it can be a window rule like `windowrule=opacity .97 .85,^(Code)$`
