### ISSUE TITLE
Extention won't perform on macOS vs Code

### ISSUE THREAD

**Issue by AsherYartsev** [hikarin522/GlassIt-VSC#5]
hey!
 I'm using macOS and have vs Code installed.
when I use the suggested shortcuts the next error log appears:
command 'glassit.increase' not found

**Comment by Exlsunshine** [comment]
Me too.

**Comment by mikeumus** [comment]
😞

**Comment by hikarin522** [comment]
#3

**Comment by tresende** [comment]
Me too
