### ISSUE TITLE
Doesn't make Visual Studio Code transparent

### ISSUE THREAD

**Issue by randomguy-2650** [hikarin522/GlassIt-VSC#53]
On Windows 11 22H2 Build 22621.2715 with Visual Studio Code version 1.84.2, and installed the `GlassIt-VSC` extension.
But when I tried to use the shortcuts `Ctrl + Alt + Z` and `Ctrl + Alt + C`, nothing initially happened. I tried changing the `glassit.alpha` value to `25`, no transparency. I even tried uninstalling Visual Studio Code and reinstalling it, and uninstalled all other extensions except for `GlassIt-VSC`, nothing happened, again. I checked what used the `Ctrl + Alt + Z` and the `Ctrl + Alt + C` extensions, only the `GlassIt-VSC` extension. I literally gave up for another two months, and tried again, nothing happened, and I was left confused.

This is probably uncommon to happen, but it happened somehow.

If needed, here's the list of my extensions installed on Visual Studio Code:

```
.NET Install Tool
Atom One Dark Theme
C/C++
C/C++ Extension Pack
C/C++ Themes
C#
C# Dev Kit
Code Runner
CodeSnap
Debugger for Java
DotENV
Error Lens
Extension Pack for Java
GlassIt-VSC
HTML CSS Support
HTML to CSS autocompletion
IntelliCode
IntelliCode API Usage Examples
IntelliCode for C# Dev Kit
JavaScript (ES6) code snippets
Language Support for Java(TM) by Red Hat
Live Preview
Live Server
Makefile Tools
Material Icon Theme
Material Theme Icons
Maven for Java
One Dark Pro
Prettier - Code formatter
Processing Language
Project Manager for Java
Pylance
Python
Test Runner for Java
Tokyo Night
vscode-icons
WSL
```

Theme: `One Dark Pro Flat`

![image](https://github.com/hikarin522/GlassIt-VSC/assets/150704902/408710e0-0a4f-4bf5-bd16-d946d90ab3d7)

I'm unsure why this didn't work and would appreciate any insights or solutions to fix this issue.

**Comment by tlarnold10** [comment]
I am getting the same issue...

**Comment by jakemayfield** [comment]
Same issue...

**Comment by maxiim3** [comment]
I am using Linux Ubuntu and i3WM. I have to reload the window and reload the window or switch back and forth to another one to get the updates

**Comment by randomguy-2650** [comment]
After messing around for a while, it works now. Closing this issue now.
