### ISSUE TITLE
GlassIt incorrectly installs remotely in Remote-SSH

### ISSUE THREAD

**Issue by erothmayer** [hikarin522/GlassIt-VSC#9]
I'm using the new Remote-SSH feature in Insiders, and GlassIt incorrectly tries to install on the remote instead of the client. When installed remotely, the extension does not work (throws errors, and does not alter the display).

I used their 'advanced' workaround to force it to install locally and it works fine, but the package needs to be updated so that it works out-of-the-box and others don't have to hunt for the workaround.

See: https://code.visualstudio.com/docs/remote/ssh for MSFT instructions on how to configure the package.

**Comment by hikarin522** [comment]
76c30d3c8b59f94219bee7c1580458dbc8960288

https://github.com/hikarin522/GlassIt-VSC/releases/tag/v0.1.5
